# Generated by Django 3.2.16 on 2023-05-19 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20230519_0805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='blog_author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='blog_content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='blog_title',
        ),
    ]
